package com.jwhi.som.domains.evt

enum class EvtOpIds(val value: UShort) {
    DISPLAY_MESSAGE(0u),
    DISPLAY_FORMATTED_MESSAGE(1u),
    SHOP_OPEN(23u),
    CHANGE_PLAYER_PARAMETER(80u),
    SET_PLAYER_PARAMETER_IN_COUNTER(84u),
    IF_COUNTER_CONDITION(140u),
    IF_MESSAGE_PROMPT(141u),
    OTHERWISE(142u),
    END_IF(143u),
    CHANGE_COUNTER(144u),
    CHANGE_PAGE(145u),
    END(UShort.MAX_VALUE),
}
